---
title: "MachineLearning"
author: "DAF"
date: '`r Sys.Date()`'
output:
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    hide: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(plyr)
library(dplyr)
library(ggplot2)
library(caret)

# set.seed(62433)
```

```{r, cache=T}
download.file("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv", "fitTrain.csv")
training = read.csv("fitTrain.csv")

download.file("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv", "fitTest.csv")
testing = read.csv("fitTest.csv")
```

```{r explore}
training %>%
    ggplot(aes(.[,5], classe, col = user_name)) +
    geom_point() +
    geom_point(data = testing, aes(.[,5], "A", col = user_name), shape = 2)
```


```{r cleanup}

trainNoTime <- training[,-c(1:7)]
# trainNoTime <- training[,-c(1, 2, 3)]

na80 <- apply(trainNoTime, 2, function(i){mean(is.na(i)) > 0.8}) %>% as.vector()

trainNA <- trainNoTime[, !na80]

# nsv <- nearZeroVar(trainNA)
# trainClean <- trainNA[,-nsv]
```


```{r preProcess}
(preProc <- preProcess(trainNoTime[,-ncol(trainNoTime)], method = c("center", "scale", "nzv", "pca"), thresh = 0.90))

trainPC <- predict(preProc, trainNoTime)
# testPC <- predict(preProc, testing)

(trainFirst <- train(classe ~., data = trainPC, method = "lda"))
```

```{r rf, cache=T}
(modelfit1 <-train(classe ~., data = trainPC, method = "rf"))
pred1 <- predict(modelfit1, newdata = trainPC)
confusionMatrix(pred1, trainPC$classe)
```

```{r gbm, cache=T}
(modelfit2 <- train(classe ~., data = trainPC, method = "gbm", verbose = F))
pred2 <- predict(modelfit2, trainPC)
confusionMatrix(pred2, trainPC$classe)
```


```{r lda, cache=T}
(modelfit3 <- train(classe ~., data = trainPC, method = "lda"))
pred3 <- predict(modelfit3, trainPC)
confusionMatrix(pred3, trainPC$classe)
```

```{r}
training %>%
    ggplot(aes(1:nrow(.), classe)) +
    geom_point(col = "red") +
    geom_point(aes(1:nrow(.), pred2), shape = 2, size = 3) +
    facet_wrap(~user_name, scale = "free")
```


```{r}
predict(modelfit2, predict(preProc, testing))

pred4 <- predict(modelfit3, newdata = testClean)

training %>%
    ggplot(aes(.[,5], classe, col = user_name)) +
    geom_point() +
    geom_point(data = training, aes(training[,5], pred, col = user_name), shape = 2, size = 5)
```


```{r}
predDF <- data.frame(pred2, pred3, classe = training$classe)
(modelfit <-train(classe ~., data = predDF, method = "rf"))
pred <- predict(modelfit, newdata = training)
confusionMatrix(pred, training$classe)

predict(modelfit, predict(preProc, testing))
```

